### ISSUE TITLE
CSS scroll snap support

### ISSUE THREAD

**Issue by yinonov** [rcbyr/keen-slider#12] opened 2020-06-20 18:58 UTC
add the use of modern CSS Scroll Snap API. it might bring a better performance.
Also a common behaviour is scrolling with mouse / pad and the slider does not react to these common gestures.

**Comment by rcbyr** [comment] 2020-06-21 05:32
Thanks for your suggestions. I'll see what I can do. As this is a duplicate of #1, I'm closing it.

**Closed by rcbyr** 2020-06-21 05:32 UTC
