### ISSUE TITLE
Jumping indexes too far with `next`

### ISSUE THREAD

**Issue by hturnbull93** [rcbyr/keen-slider#195] opened 2022-02-28 16:14 UTC
Hi there,

I'm experiencing an issue with a slider of 6 items where 4 are visible with `perView`. It seems that after moving right using `next` twice, to the last item, the `track.details.abs` goes to 2 (as it should), but then jumps to 4 for some reason. This causes attempting to move back using `prev` to go to the index 3, which doesn't work.

I'm using it in Vue/Nuxt, as so:

```vue
<template>
  <section>
    <div ref="carouselWrapper">
      <Card
        v-for="item of items"
        :key="item.name"
        class="keen-slider__slide"
        v-bind="item"
      />
    </div>

    <button @click="slider.prev()">prev</button>

    <button @click="slider.next()">next</button>
  </section>
</template>

<script>
import {
  ref,
  onMounted,
  onBeforeUnmount,
} from '@nuxtjs/composition-api'
import KeenSlider from 'keen-slider'

export default {
  name: 'MyCarousel',
  props: {
    items: {
      type: Array,
      required: true,
    },
  },
  setup(props) {
    const carouselWrapper = ref(null)
    const slider = ref()

    onMounted(() => {
      slider.value = new KeenSlider(carouselWrapper.value, {
        slides: {
          perView: 4,
          spacing: 16,
        },
        created: () => {
          setTimeout(() => {
            // update immediately after mount
            slider.value && slider.value.update()
          }, 0)
        },
      })
    })

    onBeforeUnmount(() => {
      if (slider.value) slider.value.destroy()
    })

    return {
      carouselWrapper,
      slider,
    }
  },
}
</script>
```

Am I doing something foolish? Or could this be a bug?

**Comment by rcbyr** [comment] 2022-03-01 19:25
Hey @hturnbull93 

I've created a code example (https://codesandbox.io/s/loving-hopper-o3hfgk?file=/src/Slider.vue), but could not reproduce that behavior. Which version do you use?

**Comment by hturnbull93** [comment] 2022-03-03 09:26
Hi @rcbyr , thanks for getting back to me!

We're using keen-slider ^6.6.3 with nuxt ^2.15.7. 

My colleague and I adjusted the example to be closer to our setup, but it still seems to be working fine (https://codesandbox.io/s/keen-slider-vue-testing-n0egcn)

I wonder what could be causing this, perhaps nuxt?

**Comment by ponciusz** [comment] 2022-03-03 09:39
probably connected with https://github.com/rcbyr/keen-slider/issues/181

**Comment by hturnbull93** [comment] 2022-03-03 10:44
@ponciusz that looks to be the same thing that we're experiencing!

My colleague noticed that this was happening for 5, 6, and 7 items, but not 8, which we had a hunch may be to do with some modulo maths, so we tries setting the perView to 4.001 to just nudge it out of that and it seems to be a workaround. Hardly ideal though 😅

**Comment by ponciusz** [comment] 2022-03-03 13:03
I managed to fix it by rounding number but thats not ideal i guess issue is happening when spacing is added try to remove spacing and see if your issue is there. Probably one unnecessary spacing is added with calculations.

**Comment by ponciusz** [comment] 2022-03-03 17:58
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/3374777/156623187-9b255b82-2fd1-4ef4-b61b-2daccb2eb11e.png">

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/3374777/156623800-1456bfe6-d069-4b15-8df2-8722eddc832d.png">

**Comment by DeekHalden** [comment] 2022-03-04 09:45
@rcbyr  We are facing exact the same issue and it is annoying. Please, take a look at it.

**Comment by rcbyr** [comment] 2022-03-09 21:10
Seems to be fixed by the PR from ponciusz.

**Closed by rcbyr** 2022-03-09 21:10 UTC
