### ISSUE TITLE
Bugs in after upgrading from 6.6.10 to 6.6.12

### ISSUE THREAD

**Issue by solidevolution** [rcbyr/keen-slider#225] opened 2022-05-05 16:50 UTC
We did our monthly dependency updates and got slider not working in our design system:

* slides are broken, slides are among themselves instead of side by side for horizontal scrolling
* initial loading shows slider without full width for a moment, then it loads

Our options: 

```
{
    "selector": '.slide',
    "loop": false,
    "initial": 0,
    "slides": {
        "origin": "center",
        "perView": 1.1,
        "number": null,
        "spacing": 12
    },
    "breakpoints": {
        "(min-width: 768px)": {
            "loop": false,
            "slides": {
                "origin": "center",
                "perView": 1.1,
                "number": null,
                "spacing": 24
            }
        },
        "(min-width: 1280px)": {
            "loop": false,
            "slides": {
                "origin": "auto",
                "perView": 3,
                "number": null,
                "spacing": 48
            }
        }
    },
    "rtl": false,
    "rubberband": true,
    "vertical": false,
    "renderMode": "performance"
}
```

HTML:

```
  <div class="keen-slider">
    <div class="slide">A</div>
    <div class="slide">B</div>
    <div class="slide">C</div>
  </div>
```

Imports
```
import KeenSlider, { KeenSliderInstance, KeenSliderOptions } from 'keen-slider'
import 'keen-slider/keen-slider.min.css'
```

**Comment by ponciusz** [comment] 2022-05-05 17:17
check if .keen-slider got default styles in our case it completely not including default styles.

**Comment by solidevolution** [comment] 2022-05-05 17:21
<img width="471" alt="Bildschirmfoto 2022-05-05 um 19 20 32" src="https://user-images.githubusercontent.com/6850773/166978081-8ee55f7f-2173-45b8-8d4a-9b7b062a571c.png">

This style are completely missing after version update.

**Comment by ponciusz** [comment] 2022-05-05 17:23
Ye something is wrong quick fix is to copy all styles and use from anywhere else not node_modules folder that's what we did

**Comment by ponciusz** [comment] 2022-05-05 17:24
But in my case reverting to prev version does not fix issue so might be something with other dependencies which causing it

**Comment by solidevolution** [comment] 2022-05-05 17:28
Revert to 6.6.10 works

**Comment by rcbyr** [comment] 2022-05-05 17:37
Hello @solidevolution 

I wasn't able to reproduce this error in a codesandbox. Here is a codesandbox with your settings and the current version: https://codesandbox.io/s/pensive-blackwell-vpft4e?file=/src/App.js 

Which Framework do you use? Can you give me a hint how I can reproduce that?

**Comment by ponciusz** [comment] 2022-05-05 18:46
In my case it's next.js react and I only can reproduce when building app.
 dev mode with hot reload works fine

**Comment by rcbyr** [comment] 2022-05-05 19:19
@solidevolution I've tried it with vue(2.6.10) + storybook 5 and it works. Can you give me a small repository where I can reproduce this behavior? 

@ponciusz I've tried it with next 11 and next 12 without problems in dev mode or when building? What error do you get?

**Comment by ponciusz** [comment] 2022-05-05 21:52
No error just not including styles when building app and running it

**Comment by rcbyr** [comment] 2022-05-06 03:19
@solidevolution Can you update your project to v6.6.13? I think I found the problem.

@ponciusz Since you said that going back to a previous version didn't fix the problem, I'm not sure if you're having the same bug or just the same effect. Maybe you can try the new version as well? Does including other css files work when creating your app?

**Comment by ponciusz** [comment] 2022-05-06 07:13
Looks like it's fixed now what was that? Something in npm? It was CSS was recognized as module.

**Comment by rcbyr** [comment] 2022-05-06 07:39
I've added `sideEffects`: `false` to the package.json. It seems that I should have read the webpack documentation more carefully. Unfortunately, I could not reproduce it until now.

I removed the property again.

**Closed** 2022-05-07 17:06 UTC
